In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ast #converts strings into lists

In [2]:
credits = pd.read_csv('tmdb_5000_credits.csv')
movies = pd.read_csv('tmdb_5000_movies.csv')

In [3]:
movies.head()
# first Data ko merge kry gy

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies = movies.merge(credits,on='title')

In [6]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [7]:
#wo columns jo hm rakhyy gy 
#genres
#movie_id
#keywords
#title
#overview
#releasestate(khud kam krna hy)
#cast
#crew

In [8]:
movies= movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [9]:
movies.head(3)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [10]:
#humnei ik new dataframe banana hy jsmai hmry pss movie_id , movie_title, tags hin

In [11]:
#we have to join overview, genres, keywords, cast, crew

In [12]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [13]:
movies.dropna(inplace=True)

In [14]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [15]:
movies.duplicated().sum()

0

In [16]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# my task is to convert into this 
#['Action','Adventure','FFantasy','SciFi']

In [18]:
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
       L.append(i['name'])
    return L

In [19]:
movies['genres'] = movies['genres'].apply(convert)

In [20]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [21]:
movies['keywords'] = movies['keywords'].apply(convert)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
def convert3(obj):
    L = []
    counter= 0
    for i in ast.literal_eval(obj):
        if counter!=3:
            L.append(i['name'])
            counter+=1
        else:
            break
                
    return L

In [24]:
movies['cast'] = movies['cast'].apply(convert3)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
           L.append(i['name'])
           break
    return L

In [27]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [28]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [29]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [30]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [31]:
movies.dtypes

movie_id     int64
title       object
overview    object
genres      object
keywords    object
cast        object
crew        object
dtype: object

In [32]:
#Ab hmei spaces ko khtmm krna hy
#eg Sam Worthington ko SamWorthington mai convert krna hy 
#single entity bana imp hy bcz apka model confuse ho kar koi or movie recommend krny lg jyei ga

In [33]:
movies['genres']= movies['genres'].apply( lambda x:[i.replace(" ","")for i in x])

In [34]:
movies['cast']= movies['cast'].apply( lambda x:[i.replace(" ","")for i in x])
movies['keywords']= movies['keywords'].apply( lambda x:[i.replace(" ","")for i in x])
movies['crew']= movies['crew'].apply( lambda x:[i.replace(" ","")for i in x])

In [35]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [36]:
movies['tags']= movies['overview']+movies['genres']+ movies['keywords']+movies['cast']+movies['crew']

In [37]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [38]:
newdf = movies[['movie_id','title','tags']]

In [39]:
newdf['tags'] = newdf['tags'].apply(lambda x:" ".join(x))

C:\Users\user\AppData\Local\Temp\ipykernel_19208\1297214613.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x:" ".join(x))

In [40]:
#recommeded to convert to lower cast
newdf['tags'] = newdf['tags'].apply(lambda x: x.lower())

C:\Users\user\AppData\Local\Temp\ipykernel_19208\3641633005.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(lambda x: x.lower())

In [41]:
newdf.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [42]:
import nltk

In [43]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [44]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
        return " ".join(y)

In [45]:
newdf['tags'] = newdf['tags'].apply(stem)

C:\Users\user\AppData\Local\Temp\ipykernel_19208\2040093980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf['tags'] = newdf['tags'].apply(stem)

In [46]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [47]:
 vectors = cv.fit_transform(newdf['tags']).toarray()

In [48]:
len(cv.get_feature_names())# these are the feature name jo sbsy zayada bar ay huei hain

C:\Users\user\anaconda3\Lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

1279

In [49]:
cv.get_feature_names()

['100',
 '11',
 '12',
 '15',
 '16',
 '17',
 '1910',
 '1921',
 '1950',
 '1971',
 '1982',
 '20',
 '200',
 '2009',
 '2016',
 '2046',
 '20th',
 '28',
 '400',
 '48',
 '66',
 '6th',
 '70',
 '84',
 '86',
 '88',
 'aaa',
 'aaron',
 'abbi',
 'abortionist',
 'academi',
 'accid',
 'accomplish',
 'action',
 'actress',
 'adam',
 'adapt',
 'admir',
 'admit',
 'adopt',
 'adventur',
 'advertis',
 'affabl',
 'age',
 'aged',
 'agent',
 'aibileen',
 'aidan',
 'aileen',
 'aim',
 'ajami',
 'al',
 'alan',
 'albert',
 'alcohol',
 'alex',
 'alexander',
 'alexia',
 'alic',
 'alice',
 'alien',
 'alli',
 'altruist',
 'alyssa',
 'amalia',
 'amanda',
 'ambiti',
 'america',
 'american',
 'amiabl',
 'amidst',
 'anakin',
 'andi',
 'andrew',
 'angela',
 'angie',
 'anim',
 'annabel',
 'annie',
 'anton',
 'apart',
 'approach',
 'aragorn',
 'archaeologist',
 'archetyp',
 'archiv',
 'aris',
 'arkin',
 'arm',
 'arn',
 'arrogant',
 'art',
 'arthur',
 'arti',
 'ash',
 'ashitaka',
 'aspect',
 'aspir',
 'assassin',
 'astronaut',
 'astérix',
 'athlet',
 'august',
 'aussi',
 'australian',
 'austrian',
 'author',
 'autobiograph',
 'autumn',
 'awkward',
 'ayurveda',
 'babe',
 'babi',
 'bachelor',
 'backup',
 'bahia',
 'balthazar',
 'bambi',
 'bank',
 'baptist',
 'barney',
 'barri',
 'bas',
 'base',
 'bathori',
 'batman',
 'beatric',
 'beauti',
 'beautiful',
 'becaus',
 'becca',
 'befor',
 'begin',
 'behrani',
 'believ',
 'belka',
 'bella',
 'ben',
 'benjamin',
 'berlin',
 'best',
 'beth',
 'betray',
 'better',
 'betti',
 'bi',
 'bianca',
 'biker',
 'bilbo',
 'billi',
 'billionair',
 'biograph',
 'biographi',
 'birde',
 'bizarr',
 'blend',
 'bob',
 'bobbi',
 'bolt',
 'bond',
 'boog',
 'book',
 'bore',
 'born',
 'bounc',
 'bound',
 'bounti',
 'bourn',
 'boy',
 'boyz',
 'brad',
 'brandon',
 'brave',
 'break',
 'breast',
 'bree',
 'brennan',
 'brian',
 'brick',
 'bridget',
 'brilliant',
 'britain',
 'british',
 'britt',
 'brokeback',
 'brooklyn',
 'bruce',
 'bubba',
 'buck',
 'bucum',
 'bud',
 'bueno',
 'bug',
 'bumbl',
 'burger',
 'businessman',
 'cab',
 'cabbie',
 'cadi',
 'caiu',
 'cal',
 'cale',
 'caleb',
 'calvin',
 'capitol',
 'capt',
 'captain',
 'captiv',
 'captur',
 'carl',
 'carmen',
 'carol',
 'carolin',
 'carrie',
 'cedric',
 'celest',
 'celestin',
 'centuri',
 'challeng',
 'chao',
 'chapman',
 'charl',
 'charli',
 'charlie',
 'charlott',
 'chart',
 'chauffeur',
 'cheese',
 'chelio',
 'chicago',
 'childhood',
 'chili',
 'chon',
 'chri',
 'chrissi',
 'christin',
 'christina',
 'christma',
 'chronolog',
 'chuck',
 'chucki',
 'chuckie',
 'cia',
 'cidad',
 'cindi',
 'circu',
 'citi',
 'clair',
 'clarenc',
 'clark',
 'class',
 'clay',
 'clear',
 'climb',
 'cobb',
 'cocki',
 'codi',
 'cohabit',
 'col',
 'colin',
 'colleg',
 'colonel',
 'columbu',
 'com',
 'combat',
 'come',
 'comedi',
 'commentator',
 'commerci',
 'commun',
 'complet',
 'comput',
 'conni',
 'conrad',
 'construct',
 'contact',
 'continu',
 'control',
 'conveni',
 'corki',
 'corky',
 'corpor',
 'countless',
 'cousins',
 'cover',
 'crack',
 'craig',
 'creat',
 'crew',
 'cross',
 'curs',
 'cw',
 'dahlia',
 'dale',
 'damon',
 'dan',
 'danger',
 'daniel',
 'danni',
 'danny',
 'dar',
 'dariu',
 'darren',
 'daryl',
 'date',
 'dave',
 'david',
 'dawn',
 'deadpool',
 'deal',
 'dean',
 'deckard',
 'decor',
 'dedic',
 'deep',
 'deepli',
 'deform',
 'denni',
 'dentist',
 'depress',
 'depression',
 'deputi',
 'der',
 'derek',
 'desper',
 'despit',
 'despond',
 'detect',
 'determin',
 'detroit',
 'deuc',
 'dev',
 'dex',
 'diamond',
 'diego',
 'diplomats',
 'direct',
 'director',
 'dirti',
 'discov',
 'disench',
 'disgrac',
 'dispatch',
 'district',
 'disturb',
 'doctor',
 'documentari',
 'dogtown',
 'domen',
 'don',
 'donato',
 'donna',
 'doormat',
 'dorian',
 'dorothi',
 'dorothy',
 'double',
 'doug',
 'dr',
 'dracula',
 'dragon',
 'drama',
 'dramat',
 'dramatis',
 'drawn',
 'dray',
 'dream',
 'drew',
 'drina',
 'driven',
 'driver',
 'du',
 'duet',
 'duffi',
 'duncan',
 'dunson',
 'dure',
 'dutch',
 'earli',
 'ec',
 'eccentr',
 'eddi',
 'eden',
 'edg',
 'edmond',
 'edward',
 'egyptologist',
 'eighti',
 'el',
 'elektra',
 'eliza',
 'elizabeth',
 'ell',
 'ella',
 'elli',
 'elliot',
 'elmo',
 'elsa',
 'elvi',
 'emili',
 'emma',
 'employe',
 'en',
 'end',
 'enemi',
 'enforc',
 'engin',
 'english',
 'enrag',
 'enter',
 'era',
 'eric',
 'erin',
 'errol',
 'erstwhil',
 'escap',
 'esteem',
 'estrang',
 'ethan',
 'eva',
 'evan',
 'event',
 'everi',
 'everybodi',
 'everyon',
 'everyth',
 'evil',
 'ex',
 'exactli',
 'experi',
 'explor',
 'face',
 'fact',
 'fail',
 'famili',
 'famou',
 'far',
 'fast',
 'fbi',
 'fear',
 'fed',
 'federal',
 'feel',
 'femal',
 'fifti',
 'film',
 'filmmak',
 'financi',
 'firefight',
 'flamboyantli',
 'fledgl',
 'fletcher',
 'folklor',
 'follow',
 'foolish',
 'forc',
 'ford',
 'forens',
 'forks',
 'forrest',
 'foundl',
 'fourteen',
 'fourth',
 'frame',
 'franci',
 'frank',
 'franki',
 'fred',
 'freddi',
 'freddie',
 'freddy',
 'frederick',
 'french',
 'frida',
 'friend',
 'friends',
 'frodo',
 'fugit',
 'furiou',
 'futurist',
 'gabita',
 'gabriel',
 'galaxina',
 'gang',
 'garfield',
 'gari',
 'gary',
 'gener',
 'genet',
 'geophysicist',
 'georg',
 'george',
 'georgia',
 'ghost',
 'gift',
 'gigli',
 'gilbert',
 'gile',
 'girl',
 'given',
 'glendon',
 'glengarri',
 'global',
 'god',
 'godzilla',
 'goo',
 'good',
 'gorgeou',
 'govern',
 'grace',
 'gradi',
 'greed',
 'greg',
 'gretta',
 'griev',
 'griff',
 'gritti',
 'ground',
 'grow',
 'gru',
 'gu',
 'guillermo',
 'guns',
 'gunsling',
 'gwyneth',
 'haley',
 'half',
 'hamlet',
 'hancock',
 'handsome',
 'hanna',
 'hannah',
 'hapless',
 'happi',
 'hard',
 'hardflip',
 'harper',
 'harri',
 'harriet',
 'harry',
 'harvard',
 'hassl',
 'hazen',
 'heartbeep',
 'heather',
 'heaven',
 'held',
 'helen',
 'heli',
 'henri',
 'hi',
 'hick',
 'high',
 'hilarity',
 'hire',
 'histor',
 'histori',
 'hitman',
 'holden',
 'holli',
 'hollywood',
 'home',
 'homicid',
 'hondo',
 'honey',
 'hope',
 'horty',
 'hot',
 'hotshot',
 'housewif',
 'hoyl',
 'hubert',
 'hud',
 'hugo',
 'human',
 'humans',
 'humbert',
 'huo',
 'hushpuppy',
 'ice',
 'iconoclastic',
 'ignor',
 'ike',
 'immedi',
 'immort',
 'indi',
 'indian',
 'industri',
 'innoc',
 'insan',
 'insid',
 'inspir',
 'instead',
 'inter',
 'interstellar',
 'intrepid',
 'inventor',
 'investig',
 'invis',
 'ip',
 'iri',
 'irish',
 'iron',
 'isaac',
 'isabel',
 'ivan',
 'jack',
 'jackass',
 'jacki',
 'jacq',
 'jade',
 'jake',
 'jamal',
 'jame',
 'jami',
 'jan',
 'jane',
 'jare',
 'jarhead',
 'jasmin',
 'jason',
 'jay',
 'jealous',
 'jean',
 'jeffrey',
 'jellyston',
 'jenna',
 'jep',
 'jerri',
 'jess',
 'jessica',
 'jesus',
 'jigsaw',
 'jim',
 'jimi',
 'jimmi',
 'joan',
 'joe',
 'joel',
 'joey',
 'john',
 'johnni',
 'join',
 'jonathan',
 'jordan',
 'joseph',
 'josh',
 'josie',
 'juli',
 'julia',
 'julian',
 'juliu',
 'just',
 'justice',
 'justin',
 'kaisa',
 'kale',
 'karl',
 'katherin',
 'katniss',
 'kay',
 'kazakh',
 'keong',
 'kermit',
 'kevin',
 'kid',
 'kidnapp',
 'kindheart',
 'king',
 'kinsey',
 'kline',
 'krishna',
 'kuzco',
 'kyle',
 'la',
 'lac',
 'lara',
 'larisa',
 'larri',
 'late',
 'lauri',
 'lawrenc',
 'le',
 'led',
 'lee',
 'left',
 'legendari',
 'legless',
 'lestat',
 'lester',
 'level',
 'li',
 'lif',
 'life',
 'lifelong',
 'light',
 'lightheart',
 'lightn',
 'like',
 'lil',
 'lilya',
 'liquid',
 'literatur',
 'liu',
 'live',
 'liz',
 'lizzi',
 'llewelyn',
 'lloyd',
 'lo',
 'lock',
 'lola',
 'london',
 'lone',
 'loner',
 'long',
 'longtim',
 'look',
 'loos',
 'lorrain',
 'lov',
 'love',
 'low',
 'lu',
 'luc',
 'luci',
 'luke',
 'lush',
 'luther',
 'mad',
 'madea',
 'madelin',
 'mafia',
 'maggi',
 'maggie',
 'majo',
 'major',
 'malcolm',
 'mallori',
 'man',
 'mandi',
 'manhattanit',
 'mann',
 'manny',
 'marcel',
 'marcellu',
 'marcu',
 'marguerit',
 'mari',
 'maria',
 'mario',
 'marisa',
 'mark',
 'marshal',
 'marti',
 'martin',
 'mask',
 'master',
 'match',
 'matt',
 'matthew',
 'maurice',
 'maverick',
 'max',
 'maximillian',
 'mcmaster',
 'medic',
 'meet',
 'megaforc',
 'megan',
 'melani',
 'melba',
 'melvin',
 'member',
 'men',
 'menac',
 'mental',
 'merchant',
 'mere',
 'meredith',
 'mexican',
 'mia',
 'michael',
 'michel',
 'mickey',
 'middl',
 'midler',
 'mike',
 'mild',
 'mile',
 'milo',
 'milton',
 'mina',
 'mind',
 'minion',
 'minnesota',
 'minni',
 'minor',
 'mirabel',
 'miracl',
 'miser',
 'mitch',
 'mitchel',
 'modern',
 'molière',
 'molli',
 'mom',
 'moment',
 'money',
 'monro',
 'monster',
 'morgan',
 'mort',
 'mother',
 'motherhood',
 'movi',
 'mowgli',
 'mr',
 'mulder',
 'multi',
 'multipl',
 'mumbl',
 'murderess',
 'murray',
 'music',
 'myle',
 'nacho',
 'nada',
 'naiv',
 'nanni',
 'nat',
 'natali',
 'nathan',
 'natur',
 'navi',
 'nazi',
 'neal',
 'nearli',
 'neighbor',
 'nelli',
 'nelson',
 'nemo',
 'nerdi',
 'nervou',
 'new',
 'newli',
 'newly',
 'newlyw',
 'news',
 'nick',
 'nicky',
 'nicol',
 'nicola',
 'nightclub',
 'ninja',
 'noah',
 'noni',
 'norma',
 'noth',
 'notori',
 'novale',
 'novelist',
 'nypd',
 'obsess',
 'octob',
 'offic',
 'officially',
 'old',
 'oliv',
 'olivi',
 'olli',
 'omar',
 'onc',
 'open',
 'ordinari',
 'orphan',
 'orson',
 'oscar',
 'outlaw',
 'overachiev',
 'overs',
 'packard',
 'palo',
 'paranorm',
 'pari',
 'paris',
 'parker',
 'parol',
 'passion',
 'patron',
 'patti',
 'patton',
 'paul',
 'peggi',
 'penny',
 'pete',
 'peter',
 'phil',
 'photograph',
 'pianist',
 'pierrot',
 'pinnacl',
 'place',
 'plagu',
 'platinum',
 'play',
 'playboy',
 'pleasantli',
 'pledg',
 'po',
 'pobbi',
 'poland',
 'polar',
 'polic',
 'polit',
 'poor',
 'pooti',
 'pop',
 'porter',
 'pot',
 'power',
 'predominantli',
 'prequel',
 'present',
 'presid',
 'pressur',
 'presum',
 'pride',
 'princess',
 'priscilla',
 'privat',
 'pro',
 'profession',
 'professor',
 'prot',
 'psycholog',
 'publish',
 'publisher',
 'quadriplegics',
 'quantum',
 'quentin',
 'quirki',
 'rachel',
 'radio',
 'rafael',
 'raimunda',
 'rais',
 'raju',
 'ramona',
 'rattl',
 'ray',
 'real',
 'rebelli',
 'recent',
 'recently',
 'recess',
 'record',
 'recruit',
 'red',
 'redact',
 'reel',
 'releas',
 'remak',
 'rememb',
 'renegad',
 'renton',
 'report',
 'restless',
 'retir',
 'return',
 'reuben',
 'reunit',
 'rhode',
 'rich',
 'richard',
 'rick',
 'ride',
 'rise',
 'river',
 'rizwan',
 'road',
 'roar',
 'rob',
 'robert',
 'robin',
 'rock',
 'rocket',
 'rocki',
 'rodney',
 'roger',
 'rogu',
 'romant',
 'rooki',
 'rose',
 'rowan',
 'rugrat',
 'russ',
 'russel',
 'russian',
 'ruthless',
 ...]

In [50]:
from sklearn.metrics.pairwise import cosine_similarity

In [51]:
similarity = cosine_similarity(vectors)

In [52]:
def recommend(movie):
    movie_index = newdf[newdf['title']==movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse=True,
                         key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(newdf.iloc[i[0]].title)

In [53]:
recommend('Aliens')

Pirates of the Caribbean: At World's End
Spectre
The Dark Knight Rises
John Carter
Spider-Man 3

In [54]:
import pickle

In [55]:
pickle.dump(newdf,open('movies.pkl','wb'))

In [56]:
pickle.dump(similarity,open('similarity.pkl','wb'))